version: "3"

services:
  web:
    image: carservice/nginx-php-fpm:latest
    ports:
      - "8080:80"
    volumes:
      - ${APP_CODE_PATH}:/var/www/html
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${APP_CODE_PATH}:/var/www/html
