version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: prod_mysql
    restart: unless-stopped
    volumes:
      - /datastore/docker/prod/mysql:/var/lib/mysql
      - /datastore/docker/prod/mysql/init:/docker-entrypoint-initdb.d
    env_file:
      - ./deploy/.env
    environment:
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carservice-admin-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ${PROJECT_HOST}:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql

  web:
    image: nginx:latest
    container_name: prod-nginx
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_HOST}:/var/www/html
      - ${NGINX_CONF_HOST}:/etc/nginx/conf.d/default.conf
    depends_on:
      - app