version: "3.7"

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    image: admin_app_workspace
    container_name: admin_app_workspace
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${PROJECT_PATH}:/var/www
    networks:
      - carservice
  # todo: add mysql container.
  # db:
  #   image: mysql
  #   container_name: dreamy-db
  #   restart: unless-stopped
  #   depends_on:
  #     - app_back
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: 4ztgeU%
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #   networks:
  #     - carservice
  nginx:
    image: nginx:1.25-alpine
    container_name: prod_nginx
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 8081:80
      - 443:443
    volumes:
      - ${PROJECT_PATH}:/var/www
      - ${NGINX_VHOST_DIR_PATH}:/etc/nginx/conf.d/:ro
    networks:
      - carservice
networks:
  carservice:
    driver: bridge
