version: '3'
services:
  web:
    image: nginx:latest
    container_name: carservice_nginx
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
      - ../carservice-admin.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: php:8.1-fpm
    container_name: carservice_php
    volumes:
      - ./laravel:/var/www/html
  # mysql:
  #   image: mysql:5.7
  #   container_name: laravel_mysql
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_ROOT_PASSWORD: your_root_password
  #     MYSQL_USER: your_db_user
  #     MYSQL_PASSWORD: your_db_password
  #   volumes:
  #     - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
