version: "3.7"

services:
  carservice_phptool:
    build:
      context: .
      dockerfile: Dockerfile
    image: carservice_phptool
    container_name: carservice_phptool
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${LARAVEL_PROJECT_PATH}:/var/www
    networks:
      - carservice_admin_network
  carservice_mysql:
    image: mysql:8
    container_name: carservice_mysql
    restart: unless-stopped
    depends_on:
      - carservice_phptool
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DATA_PATH}/data:/var/lib/mysql
      - ${MYSQL_DATA_PATH}/init:/docker-entrypoint-initdb.d
      # - ${MYSQL_SQL_SOURCE}:/
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - carservice_admin_network
  nginx:
    image: nginx:1.25-alpine
    container_name: prod_nginx
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 8081:80
      - 4443:443
    volumes:
      - ${LARAVEL_PROJECT_PATH}:/var/www
      - ${NGINX_VHOSTS_PATH}:/etc/nginx/conf.d/:ro
    networks:
      - carservice_admin_network
  # todo: add redis container.
networks:
  carservice_admin_network:
    driver: bridge
