version: "3.7"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: admin_application
    container_name: admin_application
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${PROJECT_PATH}:/var/www
    networks:
      - carservice
  # db:
  #   image: mysql
  #   container_name: dreamy-db
  #   restart: unless-stopped
  #   depends_on:
  #     - app_back
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: 4ztgeU%
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #   networks:
  #     - carservice
  # nginx:
  #   image: nginx:1.17-alpine
  #   container_name: dreamy-back-nginx
  #   restart: unless-stopped
  #   ports:
  #     - 8000:80
  #   volumes:
  #     - ./:/var/www
  #     - ./docker-compose/vhosts:/etc/nginx/conf.d
  #   networks:
  #     - carservice
networks:
  carservice:
    driver: bridge
